import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import "./privacy.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft } from "@fortawesome/free-solid-svg-icons";
import { Link } from "react-router-dom";
import { faInfoCircle } from "@fortawesome/free-solid-svg-icons";
import { faShieldAlt } from "@fortawesome/free-solid-svg-icons";
import { faCookie } from "@fortawesome/free-solid-svg-icons";
import Footer from "../component/footer";
function privacy() {
    return (_jsxs("div", { className: "titles", children: [_jsx("h1", { className: "text-center   fw-bold  ", style: {
                    color: '#0071b8'
                }, children: "PRIVACY POLICY " }), _jsx("div", { className: "icone1", children: _jsxs(Link, { className: " nav-link icone1", to: "./login", children: [_jsx(FontAwesomeIcon, { icon: faArrowLeft, className: " m-2   fs-6  icone2" }), " ", "click to go back"] }) }), _jsx("div", { className: "    container-fluid fs-4 w-75 text-center ", children: _jsxs("p", { className: " pt-4", children: [_jsxs("h1", { children: ["Welcome to ", _jsx("span", { style: {}, children: " Streamify" }), "!"] }), " ", "Your privacy is important to us. On this page, we provide you with all the necessary information on how we collect, use, disclose, and protect your personal information."] }) }), _jsx("div", { className: "     container-fluid text-center fs-4 w-75  ", children: _jsxs("p", { className: " pt-4 mt-5", children: [_jsx(FontAwesomeIcon, { icon: faInfoCircle, className: "fs-1" }), _jsx("h1", { children: "Collection of Information " }), "We collect information that you voluntarily provide when interacting with our website. This may include your name, email address, and other personal information you provide during registration or through forms on our site."] }) }), _jsx("div", { className: "diagonal-box", children: _jsxs("div", { className: "content fs-4 w-75 text-center  mt-5  position-relative top-25", style: {
                        color: "#0071b8",
                    }, children: [_jsx("h1", { children: " Use of Information" }), "The collected information is used to personalize your experience on our site, improve our services, and send you relevant information. We will never share your information with third parties without your consent.", _jsxs("p", { className: "  pt-4 fs-4 mt-5", children: [_jsx(FontAwesomeIcon, { icon: faShieldAlt }), _jsx("h1", { children: "Protection of Information " }), "We collect information that We take security measures to protect your personal information and ensure that it is treated securely and in compliance with applicable privacy laws."] }), _jsxs("p", { className: " mt-5 fs-4", children: [_jsx(FontAwesomeIcon, { icon: faCookie }), _jsx("h1", { className: "mt-5", children: "Cookies" }), "Our site uses cookies to enhance your browsing experience. You can control cookie acceptance through your browser settings."] })] }) }), _jsx("div", { className: " container-fluid text-center fs-3 w-75  cook   mb-5", children: _jsxs("p", { className: " fs-4", children: [_jsx("h1", { className: "", children: "tools" }), "Our site uses tools to enhance your browsing experience. You can control  settings  acceptance through your browser totally."] }) }), _jsx("div", { className: "container-fluid text-center fs-3 w-75  mb-5", children: _jsxs("p", { className: "fs-4", children: [_jsx("h1", { className: " ", children: " Links to Third-Party " }), " ", _jsx("br", {}), " Sites Our site may contain links to third-party websites. We are not responsible for the privacy practices of such sites, and we recommend reading their privacy policies. ", _jsx("br", {}), " ", _jsx("h1", { children: "Changes to the Privacy Policy " }), " ", _jsx("br", {}), " We reserve the right to make changes to this Privacy Policy. Changes will be posted on this page, so we encourage you to check it regularly. Contact Us For questions or clarifications about our Privacy Policy,", " ", _jsx("br", {}), " Thank you for trusting our site!"] }) }), _jsx(Footer, {})] }));
}
export default privacy;
