import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import './subscribe.css';
function Subscribe() {
    const [selectedOption, setSelectedOption] = useState('option1');
    const handleButtonClick = (option) => {
        setSelectedOption(option);
    };
    return (_jsxs("div", { className: "container-with-background", children: [_jsx("div", { className: "container", children: _jsx("div", { className: "row", children: _jsxs("div", { className: "col-md-4 col-sm-4 col-12 mx-auto", children: [_jsx("h1", { className: 'mov titreMovies', style: { textAlign: 'center', marginTop: '2rem' }, children: "Subscribe" }), _jsx("div", { className: "button-container", role: "group", children: _jsx("button", { className: `transi ${selectedOption === 'option2' ? 'active' : 'inactive'}`, onClick: () => handleButtonClick('option2'), children: "Monthly" }) })] }) }) }), _jsx("div", { className: 'container mx-auto mt-3', children: _jsx("div", { className: "row mt-3", children: selectedOption === 'option2' &&
                        _jsx("div", { className: "pricing-area", children: _jsx("div", { className: "container", children: _jsxs("div", { className: "row", children: [_jsx("div", { className: "col-md-4 col-sm-6 col-xs-12", children: _jsxs("div", { className: "single-price", children: [_jsxs("div", { className: "deal-top", children: [_jsx("h3", { children: "Standard" }), _jsxs("h4", { children: [" Free ", _jsx("span", { className: "sup" }), " "] })] }), _jsxs("div", { className: "deal-bottom", children: [_jsxs("ul", { className: "deal-item", children: [_jsx("li", { children: "Free access to a limited selection of content." }), _jsx("li", { children: "Light advertisements." }), _jsx("li", { children: "No long-term commitment." }), _jsx("li", { children: "Limited catalog compared to other plans." }), _jsx("li", { children: "Regular advertisements during viewing." })] }), _jsx("div", { className: "btn-area", children: _jsx("a", { href: "#", children: "Sign Up" }) })] })] }) }), _jsx("div", { className: "col-md-4 col-sm-6 col-xs-12", children: _jsxs("div", { className: "single-price", children: [_jsxs("div", { className: "deal-top", children: [_jsx("h3", { children: "Individual" }), _jsxs("h4", { children: [" 12.99 ", _jsx("span", { className: "sup", children: "$" }), " "] })] }), _jsxs("div", { className: "deal-bottom", children: [_jsxs("ul", { className: "deal-item", children: [_jsx("li", { children: "Unlimited access to the entire catalog." }), _jsx("li", { children: "High-definition streaming." }), _jsx("li", { children: "No advertisements during viewing." }), _jsx("li", { children: "Monthly payment for more flexibility." }), _jsx("li", { children: "Slightly higher monthly cost than the annual plan." })] }), _jsx("div", { className: "btn-area", children: _jsx("a", { href: "#", children: "Sign Up" }) })] })] }) }), _jsx("div", { className: "col-md-4 col-sm-12 col-12", children: _jsxs("div", { className: "single-price", children: [_jsxs("div", { className: "deal-top", children: [_jsx("h3", { children: "Family" }), _jsxs("h4", { children: [" 19.99 ", _jsx("span", { className: "sup", children: "$" }), " "] })] }), _jsxs("div", { className: "deal-bottom", children: [_jsxs("ul", { className: "deal-item", children: [_jsx("li", { children: "Unlimited access to the entire catalog for multiple users." }), _jsx("li", { children: "High-definition streaming." }), _jsx("li", { children: "No advertisements during viewing." }), _jsx("li", { children: "Parental control features." }), _jsx("li", { children: "Monthly payment for more flexibility." })] }), _jsx("div", { className: "btn-area", children: _jsx("a", { href: "#", children: "Sign Up" }) })] })] }) })] }) }) }) }) })] })
    // </div>
    );
}
export default Subscribe;
